#87 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. 

def find_fib(num):
    first_num = 1
    second_num = 2
    total = 0

    while second_num <= num:
        if second_num%2 == 0:
            total += second_num

        second_num += first_num
        first_num = second_num - first_num

    return total

def fib_even_sum():
    total = find_fib(4000000)
    print total

# fib_even_sum()
